#!/usr/bin/env bash

composer install 


if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER user1
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi

php artisan serve --host=0.0.0.0 --port=8181